package com.mmc.processors;

import com.mmc.backend.MainClass;
import com.mmc.responce.AResponce;
import com.mmc.responce.FileStreamResponce;
import com.sun.net.httpserver.HttpExchange;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;

public class FileProcessor extends AAPIProcessor {

    public FileProcessor(HttpExchange t) {
        super(t);
    }

    @Override
    public AResponce processRequest() throws Exception {
        //TO DO: Check if requeste file was generated by this session
        //InputStream is = MainClass.class.getClassLoader().getResourceAsStream(fileName);
        String fileName = t.getRequestURI().toString();
        System.out.println("    FileName=" + fileName);
        fileName="c:\\tmp\\AuthorizationHistory.pdf";
        System.out.println("    FileName=" + fileName);
        InputStream is = new FileInputStream(fileName);  //MainClass.class.getClassLoader().getResourceAsStream(fileName);
        t.getResponseHeaders().set("Content-Type", "application/pdf");
        return new FileStreamResponce(t, is);
    }

}
